# These settings are synced to GitHub by https://probot.github.io/apps/settings/
# See https://github.com/apps/settings
repository:
  has_issues: true
  has_wiki: false
  has_projects: false
labels:
  - name: automerge
    description: Automatically merge this PR
    color: ff66cc
    oldname: habx-automerge
  - name: autoupdate
    description: Automatically update this PR
    color: ff66cc
    oldname: habx-autoupdate
  - name: automerge-noupdate
    description: Merge without updating this PR
    color: cccccc
  - name: autorelease
    description: Automatically create a release after merge
    color: ff66cc
    oldname: habx-automerge
  - name: autorelease-major
    description: Automatically create a MAJOR release after merge
    color: ff66cc
  - name: dependencies
    description: Update created by dependencies
    color: 0366d6
  - name: security
    description: Pull request related to security
    color: ee0701
